name: 'ReSharper CLI InspectCode'
description: 'Inspect code with ReSharper Command Line Tool and annotate PR'
author: 'muno92'
inputs:
  solutionPath:
    required: true
    description: 'input solution file path here'
  failOnIssue:
    required: false
    default: '1'
    description: 'action fail when issue exists'
  version:
    required: false
    description: 'input solution file path here'
    default: '2021.1.5'
  minimumSeverity:
    required: false
    description: 'If set this option warning, action will fail when error or warning issue is exists.(Notice issue is annotated only.)'
    default: 'notice'
  exclude:
    required: false
    description: Set this options to specified exclude path to ReSharper CLI.
  ignoreIssueType:
    required: false
    description: Comma-separated list of ignore issue type.
  executablePath:
    required: false
    description: The path for the jb executable
    default: 'jb'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: hash
  color: orange
